name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main
on:
  push:
    branches:
      - main
 
jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        apt-get install -y python3-pip
        apt-get install -y python3-psycopg2
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install ez_setup
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .

        pip3 install git+https://${{secrets.GIT_ACCESS_TOKEN}}@github.com/martijnl00/some_functions@main#egg=some_functions --target="/usr/lib/python3/dist-packages"
        pip3 install azure-functions --target="/usr/lib/python3/dist-packages"
        pip3 install -r docs/requirements.txt --target="/usr/lib/python3/dist-packages"

      shell: bash
    
    - name: Show Working directory
      run: ls 
    - name: Show src directory
      run: ls ./src
    - name: Show site-packages directory
      run: ls /usr/lib/python3/
    - name: Show dist-packages directory
      run: ls /usr/lib/python3/dist-packages

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash