name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main
on:
  push:
    branches:
      - main
 
jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        apt-get install -y python3-pip
        pip3 install requests

        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    - name: Check out my other private repo
      uses: actions/checkout@main
      with:
        repository: martijnl00/some_functions
        path: ./dependencies
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    
    - name: Show Working directory
      run: ls ./dependencies

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash